import = [
  "~/.config/alacritty/themes/themes/github_dark.toml"
]

shell = "/bin/zsh"

[colors.primary]
background = '#000000'

[font]
size = 16.0

[window]
decorations = "Buttonless"
dynamic_padding = true
startup_mode = "Fullscreen"
